env: "local"

http_server:
  port: ":8085"
  read_timeout: 30s
  write_timeout: 30s

postgres:
  dsn: "postgres://authx_user:password123@localhost:5437/authx_db?sslmode=disable"
  max_retries: 10
  retry_interval: 5s
  connect_timeout: 30s