version: "3"

tasks:
  migrate:
    cmds:
      - task: migrate:up
    silent: true

  migrate:up:
    desc: "Apply all UP migrations for PostgreSQL"
    cmds:
      - go run ./cmd/migrator --database-dsn "postgres://authx_user:password123@localhost:5437/authx_db?sslmode=disable" --migrations-path ./migrations --command up

  migrate:down:
    desc: "Rollback the last DOWN migration for PostgreSQL"
    cmds:
      - go run ./cmd/migrator --database-dsn "postgres://authx_user:password123@localhost:5437/authx_db?sslmode=disable" --migrations-path ./migrations --command down

  server:
    desc: "Run the server"
    cmds:
      - go run ./cmd/app/main.go --config=./config/local.yaml